package com.security.entity.emp;

public class Departments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.department_id
     *
     * @mbg.generated Sun Sep 01 22:30:49 CST 2019
     */
    private Integer department_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.department_name
     *
     * @mbg.generated Sun Sep 01 22:30:49 CST 2019
     */
    private String department_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.manager_id
     *
     * @mbg.generated Sun Sep 01 22:30:49 CST 2019
     */
    private Integer manager_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.location_id
     *
     * @mbg.generated Sun Sep 01 22:30:49 CST 2019
     */
    private Integer location_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.department_id
     *
     * @return the value of departments.department_id
     *
     * @mbg.generated Sun Sep 01 22:30:49 CST 2019
     */
    public Integer getDepartment_id() {
        return department_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.department_id
     *
     * @param department_id the value for departments.department_id
     *
     * @mbg.generated Sun Sep 01 22:30:49 CST 2019
     */
    public void setDepartment_id(Integer department_id) {
        this.department_id = department_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.department_name
     *
     * @return the value of departments.department_name
     *
     * @mbg.generated Sun Sep 01 22:30:49 CST 2019
     */
    public String getDepartment_name() {
        return department_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.department_name
     *
     * @param department_name the value for departments.department_name
     *
     * @mbg.generated Sun Sep 01 22:30:49 CST 2019
     */
    public void setDepartment_name(String department_name) {
        this.department_name = department_name == null ? null : department_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.manager_id
     *
     * @return the value of departments.manager_id
     *
     * @mbg.generated Sun Sep 01 22:30:49 CST 2019
     */
    public Integer getManager_id() {
        return manager_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.manager_id
     *
     * @param manager_id the value for departments.manager_id
     *
     * @mbg.generated Sun Sep 01 22:30:49 CST 2019
     */
    public void setManager_id(Integer manager_id) {
        this.manager_id = manager_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.location_id
     *
     * @return the value of departments.location_id
     *
     * @mbg.generated Sun Sep 01 22:30:49 CST 2019
     */
    public Integer getLocation_id() {
        return location_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.location_id
     *
     * @param location_id the value for departments.location_id
     *
     * @mbg.generated Sun Sep 01 22:30:49 CST 2019
     */
    public void setLocation_id(Integer location_id) {
        this.location_id = location_id;
    }
}